"""initial schema

Revision ID: 1968672b7c4e
Revises:
Create Date: 2026-08-30 05:23:14.647217+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1968672b7c4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('transfer_number', sa.String(length=20), nullable=True),
    sa.Column('menu_url', sa.String(length=500), nullable=True),
    sa.Column('ai_greeting', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurants_is_active'), 'restaurants', ['is_active'], unique=False)
    op.create_index(op.f('ix_restaurants_name'), 'restaurants', ['name'], unique=False)
    op.create_index(op.f('ix_restaurants_phone_number'), 'restaurants', ['phone_number'], unique=False)
    op.create_table('calls',
    sa.Column('call_sid', sa.String(length=100), nullable=False),
    sa.Column('caller_number', sa.String(length=20), nullable=False),
    sa.Column('called_number', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Enum('FAQ_ANSWERED', 'RESERVATION_CREATED', 'CALL_TRANSFERRED', 'HUMAN_ESCALATION', 'CALL_ABANDONED', 'UNKNOWN', name='calloutcomeenum'), nullable=False),
    sa.Column('was_transferred', sa.Boolean(), nullable=False),
    sa.Column('was_escalated', sa.Boolean(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('recording_path', sa.String(length=500), nullable=True),
    sa.Column('call_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_call_restaurant_outcome', 'calls', ['restaurant_id', 'outcome'], unique=False)
    op.create_index('idx_call_restaurant_time', 'calls', ['restaurant_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_calls_call_sid'), 'calls', ['call_sid'], unique=True)
    op.create_index(op.f('ix_calls_called_number'), 'calls', ['called_number'], unique=False)
    op.create_index(op.f('ix_calls_caller_number'), 'calls', ['caller_number'], unique=False)
    op.create_index(op.f('ix_calls_outcome'), 'calls', ['outcome'], unique=False)
    op.create_index(op.f('ix_calls_restaurant_id'), 'calls', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_calls_start_time'), 'calls', ['start_time'], unique=False)
    op.create_index(op.f('ix_calls_was_escalated'), 'calls', ['was_escalated'], unique=False)
    op.create_index(op.f('ix_calls_was_transferred'), 'calls', ['was_transferred'], unique=False)
    op.create_table('reservations',
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('reservation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reservation_time', sa.String(length=5), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'DECLINED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', name='reservationstatusenum'), nullable=False),
    sa.Column('call_sid', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reservation_restaurant_date', 'reservations', ['restaurant_id', 'reservation_date'], unique=False)
    op.create_index('idx_reservation_restaurant_status', 'reservations', ['restaurant_id', 'status'], unique=False)
    op.create_index(op.f('ix_reservations_call_sid'), 'reservations', ['call_sid'], unique=False)
    op.create_index(op.f('ix_reservations_customer_email'), 'reservations', ['customer_email'], unique=False)
    op.create_index(op.f('ix_reservations_customer_name'), 'reservations', ['customer_name'], unique=False)
    op.create_index(op.f('ix_reservations_customer_phone'), 'reservations', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_reservations_reservation_date'), 'reservations', ['reservation_date'], unique=False)
    op.create_index(op.f('ix_reservations_restaurant_id'), 'reservations', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_table('restaurant_faqs',
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_faq_restaurant_category', 'restaurant_faqs', ['restaurant_id', 'category'], unique=False)
    op.create_index(op.f('ix_restaurant_faqs_category'), 'restaurant_faqs', ['category'], unique=False)
    op.create_index(op.f('ix_restaurant_faqs_is_active'), 'restaurant_faqs', ['is_active'], unique=False)
    op.create_index(op.f('ix_restaurant_faqs_question'), 'restaurant_faqs', ['question'], unique=False)
    op.create_index(op.f('ix_restaurant_faqs_restaurant_id'), 'restaurant_faqs', ['restaurant_id'], unique=False)
    op.create_table('restaurant_hours',
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('opening_time', sa.String(length=5), nullable=False),
    sa.Column('closing_time', sa.String(length=5), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'day_of_week', name='uq_restaurant_day')
    )
    op.create_index('idx_hours_restaurant_day', 'restaurant_hours', ['restaurant_id', 'day_of_week'], unique=False)
    op.create_index(op.f('ix_restaurant_hours_restaurant_id'), 'restaurant_hours', ['restaurant_id'], unique=False)
    op.create_table('restaurant_knowledge_documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('vector_ids', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_restaurant_type', 'restaurant_knowledge_documents', ['restaurant_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_restaurant_knowledge_documents_document_type'), 'restaurant_knowledge_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_restaurant_knowledge_documents_is_active'), 'restaurant_knowledge_documents', ['is_active'], unique=False)
    op.create_index(op.f('ix_restaurant_knowledge_documents_restaurant_id'), 'restaurant_knowledge_documents', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_restaurant_knowledge_documents_title'), 'restaurant_knowledge_documents', ['title'], unique=False)
    op.create_table('restaurant_phone_numbers',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('twilio_sid', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_phone_restaurant_id', 'restaurant_phone_numbers', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_restaurant_phone_numbers_is_active'), 'restaurant_phone_numbers', ['is_active'], unique=False)
    op.create_index(op.f('ix_restaurant_phone_numbers_phone_number'), 'restaurant_phone_numbers', ['phone_number'], unique=True)
    op.create_index(op.f('ix_restaurant_phone_numbers_restaurant_id'), 'restaurant_phone_numbers', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_restaurant_phone_numbers_twilio_sid'), 'restaurant_phone_numbers', ['twilio_sid'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PLATFORM_ADMIN', 'RESTAURANT_OWNER', 'RESTAURANT_MANAGER', 'RESTAURANT_STAFF', name='userroleenum'), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_restaurant_active', 'users', ['restaurant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_restaurant_time', 'audit_logs', ['restaurant_id', 'created_at'], unique=False)
    op.create_index('idx_audit_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_restaurant_id'), 'audit_logs', ['restaurant_id'], unique=False)
    op.create_table('call_events',
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_call_time', 'call_events', ['call_id', 'timestamp'], unique=False)
    op.create_index('idx_event_type', 'call_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_call_events_call_id'), 'call_events', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_events_event_type'), 'call_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_call_events_restaurant_id'), 'call_events', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_call_events_timestamp'), 'call_events', ['timestamp'], unique=False)
    op.create_table('call_transcripts',
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transcript_call_time', 'call_transcripts', ['call_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_call_transcripts_call_id'), 'call_transcripts', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_transcripts_restaurant_id'), 'call_transcripts', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_call_transcripts_timestamp'), 'call_transcripts', ['timestamp'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_restaurant_sent', 'notifications', ['restaurant_id', 'is_sent'], unique=False)
    op.create_index('idx_notification_type', 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_is_sent'), 'notifications', ['is_sent'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_recipient'), 'notifications', ['recipient'], unique=False)
    op.create_index(op.f('ix_notifications_restaurant_id'), 'notifications', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_restaurant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_sent'), table_name='notifications')
    op.drop_index('idx_notification_type', table_name='notifications')
    op.drop_index('idx_notification_restaurant_sent', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_call_transcripts_timestamp'), table_name='call_transcripts')
    op.drop_index(op.f('ix_call_transcripts_restaurant_id'), table_name='call_transcripts')
    op.drop_index(op.f('ix_call_transcripts_call_id'), table_name='call_transcripts')
    op.drop_index('idx_transcript_call_time', table_name='call_transcripts')
    op.drop_table('call_transcripts')
    op.drop_index(op.f('ix_call_events_timestamp'), table_name='call_events')
    op.drop_index(op.f('ix_call_events_restaurant_id'), table_name='call_events')
    op.drop_index(op.f('ix_call_events_event_type'), table_name='call_events')
    op.drop_index(op.f('ix_call_events_call_id'), table_name='call_events')
    op.drop_index('idx_event_type', table_name='call_events')
    op.drop_index('idx_event_call_time', table_name='call_events')
    op.drop_table('call_events')
    op.drop_index(op.f('ix_audit_logs_restaurant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_action', table_name='audit_logs')
    op.drop_index('idx_audit_restaurant_time', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_restaurant_active', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_restaurant_phone_numbers_twilio_sid'), table_name='restaurant_phone_numbers')
    op.drop_index(op.f('ix_restaurant_phone_numbers_restaurant_id'), table_name='restaurant_phone_numbers')
    op.drop_index(op.f('ix_restaurant_phone_numbers_phone_number'), table_name='restaurant_phone_numbers')
    op.drop_index(op.f('ix_restaurant_phone_numbers_is_active'), table_name='restaurant_phone_numbers')
    op.drop_index('idx_phone_restaurant_id', table_name='restaurant_phone_numbers')
    op.drop_table('restaurant_phone_numbers')
    op.drop_index(op.f('ix_restaurant_knowledge_documents_title'), table_name='restaurant_knowledge_documents')
    op.drop_index(op.f('ix_restaurant_knowledge_documents_restaurant_id'), table_name='restaurant_knowledge_documents')
    op.drop_index(op.f('ix_restaurant_knowledge_documents_is_active'), table_name='restaurant_knowledge_documents')
    op.drop_index(op.f('ix_restaurant_knowledge_documents_document_type'), table_name='restaurant_knowledge_documents')
    op.drop_index('idx_doc_restaurant_type', table_name='restaurant_knowledge_documents')
    op.drop_table('restaurant_knowledge_documents')
    op.drop_index(op.f('ix_restaurant_hours_restaurant_id'), table_name='restaurant_hours')
    op.drop_index('idx_hours_restaurant_day', table_name='restaurant_hours')
    op.drop_table('restaurant_hours')
    op.drop_index(op.f('ix_restaurant_faqs_restaurant_id'), table_name='restaurant_faqs')
    op.drop_index(op.f('ix_restaurant_faqs_question'), table_name='restaurant_faqs')
    op.drop_index(op.f('ix_restaurant_faqs_is_active'), table_name='restaurant_faqs')
    op.drop_index(op.f('ix_restaurant_faqs_category'), table_name='restaurant_faqs')
    op.drop_index('idx_faq_restaurant_category', table_name='restaurant_faqs')
    op.drop_table('restaurant_faqs')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_restaurant_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_reservation_date'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_customer_phone'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_customer_name'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_customer_email'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_call_sid'), table_name='reservations')
    op.drop_index('idx_reservation_restaurant_status', table_name='reservations')
    op.drop_index('idx_reservation_restaurant_date', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_calls_was_transferred'), table_name='calls')
    op.drop_index(op.f('ix_calls_was_escalated'), table_name='calls')
    op.drop_index(op.f('ix_calls_start_time'), table_name='calls')
    op.drop_index(op.f('ix_calls_restaurant_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_outcome'), table_name='calls')
    op.drop_index(op.f('ix_calls_caller_number'), table_name='calls')
    op.drop_index(op.f('ix_calls_called_number'), table_name='calls')
    op.drop_index(op.f('ix_calls_call_sid'), table_name='calls')
    op.drop_index('idx_call_restaurant_time', table_name='calls')
    op.drop_index('idx_call_restaurant_outcome', table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_restaurants_phone_number'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_name'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_is_active'), table_name='restaurants')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
